/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Container;
import javax.swing.JTextField;


/**
 *
 * @author Siul
 */
public class SudokuGenetico extends javax.swing.JFrame {
    
    Container c = getContentPane();
    JTextField[] casillas = new JTextField[81];     // vector de casillas del tablero

    public SudokuGenetico() {
        initComponents();
        
        initComponents();
        
        int posx, posy;
        int[] sudockuInt = new int[81];
        
        // genera el tablero
        posx = 200;
        
        for(int i=0; i<9; i++){
            
            posy = -10;
            
            for(int j=0; j<9; j++){
                casillas[(9*i)+j] = new JTextField();
                casillas[(9*i)+j].setText("");
                
                if((j)%3 == 0){
                    posy += 45;
                }
                else{
                    posy += 35;
                }
                    
                casillas[(9*i)+j].setBounds(posx, posy, 30, 30);

                c.add(casillas[(9*i)+j]);
            }
            
            if((i)%3 == 0){
                posx += 45;
            }
            else{
                posx += 35;
            }
        }
        
        for(int i=0; i<15; i++){
            if(!casillas[i].getText().equals("")){
                sudockuInt[i]= Integer.parseInt(casillas[i].getText());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGenetico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
